### ISSUE TITLE
Consider using official VT py library 

### ISSUE THREAD

**Issue by taraxvoid** [vithakur/ragno#2]
It may be cleaner to use the official py library for the calls, for instance:
https://virustotal.github.io/vt-py/api/client.html#vt.Client.get_json

This would ensure compatibility with future API changes / versioning, and abstracts away the implementation details from the client

It also removes the need to do API key checking on the client-side, as we would be wrapping the vt.Client calls to catch `vt.error.APIError`

I can make a PR for this

**Comment by malienist** [comment]
sounds great! chuck in a PR mate.
